# Generated by Django 5.2.9 on 2025-12-09 15:32

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DICAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='DIC Analysis', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'В процессе'), ('completed', 'Завершено'), ('error', 'Ошибка'), ('cancelled', 'Отменено')], default='pending', max_length=20)),
                ('subset_size', models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(21), django.core.validators.MaxValueValidator(31)])),
                ('step', models.IntegerField(default=12)),
                ('max_iter', models.IntegerField(default=35)),
                ('min_correlation', models.FloatField(default=0.4)),
                ('image_before', models.ImageField(upload_to='uploads/before/')),
                ('image_after', models.ImageField(upload_to='uploads/after/')),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('result_image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('original_image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('deformed_image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('displacement_map_path', models.CharField(blank=True, max_length=500, null=True)),
                ('mean_displacement', models.FloatField(blank=True, null=True)),
                ('max_displacement', models.FloatField(blank=True, null=True)),
                ('median_displacement', models.FloatField(blank=True, null=True)),
                ('std_displacement', models.FloatField(blank=True, null=True)),
                ('correlation_quality', models.FloatField(blank=True, null=True)),
                ('reliable_points_percentage', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_traceback', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'DIC анализ',
                'verbose_name_plural': 'DIC анализы',
                'ordering': ['-created_at'],
            },
        ),
    ]
