# Generated by Django 5.1.2 on 2026-03-25 22:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DIC Analysis', max_length=255, verbose_name='Название задачи')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'В процессе'), ('completed', 'Завершено'), ('error', 'Ошибка'), ('cancelled', 'Отменено')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_traceback', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Задача анализа',
                'verbose_name_plural': 'Задачи анализа',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Образец', max_length=255, verbose_name='Наименование образца')),
                ('material', models.CharField(blank=True, max_length=255, null=True, verbose_name='Материал')),
                ('manufacture', models.CharField(blank=True, max_length=255, null=True, verbose_name='Изготовитель')),
                ('test_date', models.DateField(blank=True, null=True, verbose_name='Дата испытания образца')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Образец',
                'verbose_name_plural': 'Образцы',
            },
        ),
        migrations.CreateModel(
            name='AnalysisResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_json', models.JSONField(blank=True, null=True, verbose_name='JSON результаты')),
                ('mean_displacement', models.FloatField(blank=True, null=True, verbose_name='Среднее перемещение')),
                ('max_displacement', models.FloatField(blank=True, null=True, verbose_name='Макс. перемещение')),
                ('median_displacement', models.FloatField(blank=True, null=True, verbose_name='Медианное перемещение')),
                ('std_displacement', models.FloatField(blank=True, null=True, verbose_name='Стандартное отклонение')),
                ('correlation_quality', models.FloatField(blank=True, null=True, verbose_name='Качество корреляции')),
                ('reliable_points_percentage', models.FloatField(blank=True, null=True, verbose_name='Процент надёжных точек')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='dic_api.analysistask', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Результат анализа',
                'verbose_name_plural': 'Результаты анализа',
            },
        ),
        migrations.CreateModel(
            name='AnalysisParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subset_size', models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(21), django.core.validators.MaxValueValidator(31)], verbose_name='Размер подмножества')),
                ('step', models.IntegerField(default=12, verbose_name='Шаг сканирования')),
                ('max_iter', models.IntegerField(default=35, verbose_name='Макс. итераций')),
                ('min_correlation', models.FloatField(default=0.4, verbose_name='Мин. корреляция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='dic_api.analysistask', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Параметры анализа',
                'verbose_name_plural': 'Параметры анализа',
            },
        ),
        migrations.CreateModel(
            name='AnalysisImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_before', models.ImageField(upload_to='uploads/before/', verbose_name='Изображение до')),
                ('image_after', models.ImageField(upload_to='uploads/after/', verbose_name='Изображение после')),
                ('result_image_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь к результату')),
                ('original_image_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь к оригиналу')),
                ('deformed_image_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь к деформированному')),
                ('displacement_map_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь к карте перемещений')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dic_api.analysistask', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Изображения анализа',
                'verbose_name_plural': 'Изображения анализа',
            },
        ),
        migrations.AddField(
            model_name='analysistask',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='dic_api.sample', verbose_name='Образец'),
        ),
    ]
