# Generated by Django 4.2.16 on 2025-12-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dic_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicanalysis',
            name='manufacture',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Изготавитель'),
        ),
        migrations.AddField(
            model_name='dicanalysis',
            name='material',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='dicanalysis',
            name='sample_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование образца'),
        ),
        migrations.AddField(
            model_name='dicanalysis',
            name='test_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата испытания образца'),
        ),
    ]
