server {
  listen 80;
  server_name _;

  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  location /flower/ {
    proxy_pass http://flower:5555/;
    sub_filter /static/ /flower/static/;
    sub_filter_once off;
    sub_filter_types text/html;
  }

  location /flower/static/ {
    proxy_pass http://flower:5555/static/;
  }

  location /static/ {
    proxy_pass http://backend:8000/static/;
  }

  location /media/ {
    proxy_pass http://backend:8000/media/;
  }

  location /static/admin/ {
    proxy_pass http://backend:8000/static/admin/;
  }

  location /admin/ {
    proxy_pass http://backend:8000/admin/;
    proxy_pass_request_headers on;
    proxy_set_header Authorization $http_authorization;
  }

  location /api/admin/ {
    proxy_pass http://backend:8000/admin/;
    proxy_pass_request_headers on;
    proxy_set_header Authorization $http_authorization;
  }

  location /api/ {
    proxy_pass http://backend:8000/api/;
    proxy_pass_request_headers on;
    proxy_set_header Authorization $http_authorization;
  }

  location = /ucrp {
    return 301 /ucrp/;
  }

  location /ucrp/ {
    alias /usr/share/nginx/html/ucrp/;
    try_files $uri $uri/ /ucrp/index.html;
  }

  location = /dic {
    return 301 /dic/;
  }

  location /dic/ {
    alias /usr/share/nginx/html/dic/;
    try_files $uri $uri/ /dic/index.html;
  }

  location = / {
    return 302 /dic/;
  }
}