# Generated by Django 5.1.2 on 2026-04-05 19:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EPGCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('ОТ4', 'ОТ4 - Титановый сплав'), ('ВТ6', 'ВТ6 / ВТ-6 / ВТ6С - Титановый сплав Ti-6Al-4V'), ('ЭП741НП', 'ЭП741НП - Жаропрочный никелевый сплав')], default='ОТ4', max_length=20, verbose_name='Материал (сплав)')),
                ('diameter', models.FloatField(default=58.0, help_text='мм, диапазон: 54.0–60.0', validators=[django.core.validators.MinValueValidator(54.0), django.core.validators.MaxValueValidator(60.0)], verbose_name='Диаметр электрода')),
                ('length', models.FloatField(default=700.0, help_text='мм, диапазон: 650.0–720.0', validators=[django.core.validators.MinValueValidator(650.0), django.core.validators.MaxValueValidator(720.0)], verbose_name='Длина электрода')),
                ('mass_total', models.FloatField(default=66.0, help_text='кг (справочное поле)', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(300.0)], verbose_name='Общая масса электрода')),
                ('I_target', models.FloatField(default=1390.0, help_text='А (Ампер)', validators=[django.core.validators.MinValueValidator(1150.0), django.core.validators.MaxValueValidator(1600.0)], verbose_name='Целевой ток плазменной дуги')),
                ('n_electrode', models.FloatField(default=30000.0, help_text='об/мин', validators=[django.core.validators.MinValueValidator(27000.0), django.core.validators.MaxValueValidator(34400.0)], verbose_name='Скорость вращения электрода')),
                ('plasma_offset', models.FloatField(default=0.0, help_text='мм от центра', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)], verbose_name='Смещение плазменной дуги')),
                ('plasma_angle', models.FloatField(default=86.0, help_text='градусы', validators=[django.core.validators.MinValueValidator(70.0), django.core.validators.MaxValueValidator(95.0)], verbose_name='Угол падения плазменной дуги')),
                ('gas_flow', models.FloatField(default=2.6, help_text='л/с', validators=[django.core.validators.MinValueValidator(2.0), django.core.validators.MaxValueValidator(3.0)], verbose_name='Расход защитного газа')),
                ('pusher_speed', models.FloatField(default=45.0, help_text='мм/мин', validators=[django.core.validators.MinValueValidator(35.0), django.core.validators.MaxValueValidator(60.0)], verbose_name='Скорость подачи электрода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата расчёта')),
            ],
            options={
                'verbose_name': 'Расчёт ЭПГ',
                'verbose_name_plural': 'Расчёты ЭПГ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EPGAuxiliaryParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibration_level', models.FloatField(default=2.0, help_text='мм/с (>3.2 = опасно)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Уровень вибрации')),
                ('n_ogark', models.FloatField(default=26000.0, help_text='об/мин', validators=[django.core.validators.MinValueValidator(23000.0), django.core.validators.MaxValueValidator(30000.0)], verbose_name='Скорость вращения огарка')),
                ('time_from_last_cleaning', models.IntegerField(default=0, help_text='циклов', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Плавок с чистки сопла')),
                ('roller_wear_mm', models.FloatField(default=0.0, help_text='мм', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.5)], verbose_name='Износ прижимного ролика')),
                ('ambient_T', models.FloatField(default=20.0, help_text='°C (не используется)', validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(45.0)], verbose_name='Температура в цехе')),
                ('calculation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auxiliary_params', to='ucrp.epgcalculation', verbose_name='Расчёт')),
            ],
            options={
                'verbose_name': 'Вспомогательные параметры ЭПГ',
                'verbose_name_plural': 'Вспомогательные параметры ЭПГ',
            },
        ),
        migrations.CreateModel(
            name='EPGInternalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_profile', models.JSONField(blank=True, help_text='массив [float], °C', null=True, verbose_name='Температурный профиль')),
                ('d_g_profile', models.JSONField(blank=True, help_text='массив [float], мкм', null=True, verbose_name='Профиль размера гранул')),
                ('losses_profile', models.JSONField(blank=True, help_text='массив [float], %', null=True, verbose_name='Профиль потерь')),
                ('N_segments', models.IntegerField(blank=True, help_text='шт (обычно 14–15)', null=True, verbose_name='Количество сегментов')),
                ('calculation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internal_data', to='ucrp.epgcalculation', verbose_name='Расчёт')),
            ],
            options={
                'verbose_name': 'Промежуточные данные ЭПГ',
                'verbose_name_plural': 'Промежуточные данные ЭПГ',
            },
        ),
        migrations.CreateModel(
            name='EPGRecommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendations', models.JSONField(blank=True, help_text='список строк [str]', null=True, verbose_name='Рекомендации')),
                ('calculation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='ucrp.epgcalculation', verbose_name='Расчёт')),
            ],
            options={
                'verbose_name': 'Рекомендации ЭПГ',
                'verbose_name_plural': 'Рекомендации ЭПГ',
            },
        ),
        migrations.CreateModel(
            name='EPGResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_losses_pct', models.FloatField(blank=True, help_text='% за плавку, идеал <10%', null=True, verbose_name='Прогнозируемые потери')),
                ('predicted_grain_size', models.FloatField(blank=True, help_text='мкм, целевой: 100–140', null=True, verbose_name='Размер гранулы')),
                ('frac_100_140_pct', models.FloatField(blank=True, help_text='% целевой фракции, идеал >85%', null=True, verbose_name='Доля гранул 100–140 мкм')),
                ('stability_index', models.FloatField(blank=True, help_text='баллы 0–100', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Индекс стабильности')),
                ('optimal_I_by_length', models.JSONField(blank=True, help_text='массив [float], А', null=True, verbose_name='Рекомендуемый ток по длине')),
                ('optimal_n_by_length', models.JSONField(blank=True, help_text='массив [float], об/мин', null=True, verbose_name='Рекомендуемая скорость по длине')),
                ('x_grid', models.JSONField(blank=True, help_text='массив [float], мм', null=True, verbose_name='Координаты сегментов')),
                ('calculation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ucrp.epgcalculation', verbose_name='Расчёт')),
            ],
            options={
                'verbose_name': 'Результаты ЭПГ',
                'verbose_name_plural': 'Результаты ЭПГ',
            },
        ),
        migrations.CreateModel(
            name='EPGWarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposits', models.BooleanField(default=False, help_text='Капли прилипают к стенкам', verbose_name='Риск налипаний')),
                ('vibration', models.BooleanField(default=False, help_text='Вибрация >3.2 мм/с', verbose_name='Превышение вибрации')),
                ('cracking', models.BooleanField(default=False, help_text='Риск раскрытия электрода', verbose_name='Риск растрескивания')),
                ('overheating', models.BooleanField(default=False, help_text='Температура выше безопасной', verbose_name='Перегрев')),
                ('calculation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warnings_data', to='ucrp.epgcalculation', verbose_name='Расчёт')),
            ],
            options={
                'verbose_name': 'Предупреждения ЭПГ',
                'verbose_name_plural': 'Предупреждения ЭПГ',
            },
        ),
    ]
