# Generated by Django 5.1.2 on 2026-04-14 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ucrp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EPGRecommendations',
        ),
    ]
